## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_IG {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:07:02.735Z"
  }
  display_name = "IG"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_odinikesh.id
}

resource oci_core_subnet export_odipublic {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:06:54.818Z"
  }
  dhcp_options_id = oci_core_vcn.export_odinikesh.default_dhcp_options_id
  display_name    = "odipublic"
  dns_label       = "odipublic"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_odinikesh.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_odinikesh.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_odinikesh.id
}

/*resource oci_core_private_ip export_dp-agent-bom-POOL-eFFS-AP-MUMBAI-1-AD-1-sFQxMI0G {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "dataintegration"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:11:02.654Z"
  }
  display_name = "dp-agent-bom-POOL-eFFS-AP-MUMBAI-1-AD-1-sFQxMI0G"
  freeform_tags = {
  }
  hostname_label = "dp-agent-bom-pool-effs-ap-mumbai-1-ad-1-sfqxmi0g"
  ip_address     = "10.0.0.26"
  #vlan_id = <<Optional value not found in discovery>>
  #vnic_id = "ocid1.vnic.oc1.ap-mumbai-1.abrg6ljrsyeycnls2z6v6hnvtxv3nbp7xpgkdvl45dyzdywodhlnjawj634a"
}

resource oci_core_private_ip export_dp-agent-bom-POOL-eFFS-AP-MUMBAI-1-AD-1-dDjEqncH {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "dataintegration"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:14:51.475Z"
  }
  display_name = "dp-agent-bom-POOL-eFFS-AP-MUMBAI-1-AD-1-dDjEqncH"
  freeform_tags = {
  }
  hostname_label = "dp-agent-bom-pool-effs-ap-mumbai-1-ad-1-ddjeqnch"
  ip_address     = "10.0.0.244"
  #vlan_id = <<Optional value not found in discovery>>
  #vnic_id = "ocid1.vnic.oc1.ap-mumbai-1.abrg6ljr4sknnzf5otwalfcwh6dzo54rqw3pt7hc2uubiqay6onjeujvk2mq"
}*/

resource oci_core_vcn export_odinikesh {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:06:37.381Z"
  }
  display_name = "odinikesh"
  dns_label    = "odinikesh"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_vcn export_test {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-08-10T12:36:36.253Z"
  }
  display_name = "test"
  dns_label    = "trst"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-odinikesh {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:06:37.381Z"
  }
  display_name     = "Default DHCP Options for odinikesh"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_odinikesh.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "odinikesh.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-odinikesh {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:06:37.381Z"
  }
  display_name = "Default Route Table for odinikesh"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_odinikesh.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_IG.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_default_security_list export_Default-Security-List-for-odinikesh {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-09-20T10:06:37.381Z"
  }
  display_name = "Default Security List for odinikesh"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_odinikesh.default_security_list_id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-08-10T12:36:36.253Z"
  }
  display_name     = "Default DHCP Options for test"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_test.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "trst.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-08-10T12:36:36.253Z"
  }
  display_name = "Default Route Table for test"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_test.default_route_table_id
}

resource oci_core_default_security_list export_Default-Security-List-for-test {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/nikesh.g.gogia@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-08-10T12:36:36.253Z"
  }
  display_name = "Default Security List for test"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_test.default_security_list_id
}

